// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Verdant Coast LLC — https://verdantcoast.com
//
// 1024 short, friendly, lowercase English words used for generating 3-word
// admin passphrases (e.g. "apple-town-blue").
// Entropy per passphrase: log2(1024^3) = 30 bits.

export const WORDLIST: readonly string[] = [
  "acorn","admire","agile","album","alert","allow","almond","alpha","amigo","amulet","angel","ankle","apple","apron","arctic","arise",
  "armor","arrow","artist","aster","atlas","attic","audio","aunt","avenue","award","axis","baby","bacon","badge","baker","balcony",
  "banana","banjo","barn","barrel","basket","batch","bay","bead","bean","bear","beauty","bee","beetle","bench","beryl","better",
  "biome","bird","biscuit","blade","blink","bliss","block","blow","bluff","board","boat","bold","bone","bonsai","book","boot",
  "borrow","bottle","bow","box","brain","branch","brave","breeze","bride","bright","brisk","broil","bronze","broom","brown","brush",
  "bucket","buddy","buffet","bugle","bulb","bumper","bundle","bunny","burro","bush","butter","byway","cactus","cadet","cake","calm",
  "camera","canal","candid","candle","cane","canopy","cap","capital","caramel","caravan","cargo","carpet","carrot","carve","cascade","castle",
  "cattle","cedar","center","chair","chalk","channel","chapel","chart","cheer","chef","cherry","chestnut","chief","chime","chipper","choir",
  "choose","chow","church","cinema","circle","citrus","city","clarity","clause","clean","clever","cliff","climb","clock","cloud","club",
  "coach","coast","cobalt","cocoa","coffee","collar","color","colt","comet","comic","compass","coo","cool","copper","cord","corn",
  "cosmic","cotton","cougar","couple","court","coyote","crab","craft","crane","crayon","create","creek","crew","crimson","crisp","crop",
  "crown","crumb","crush","cube","cucumber","cue","cup","curio","curry","custom","cycle","cypress","daisy","dandy","dare","dark",
  "dawn","dear","deer","delta","denim","derby","design","detail","diamond","digital","dip","direct","dish","divine","doctor","dog",
  "donkey","donut","dots","dough","drawer","dress","drum","duck","duke","dusk","eager","earn","earth","easy","eclair","edit",
  "effort","elbow","elder","elegant","elephant","elf","elk","elope","elven","emerald","empire","end","enjoy","equal","erase","escape",
  "ethics","evening","exam","except","expert","fable","face","fair","faith","falcon","famous","fang","farm","fashion","fauna","fawn",
  "feature","fennel","festival","fiber","field","fig","filter","finch","finish","fire","fish","five","fizz","flair","flask","flavor",
  "flax","flicker","flint","flock","flour","flower","flute","foal","fog","folk","fond","foot","force","forge","formal","fossil",
  "fountain","fox","fractal","fresco","friend","frisbee","front","froth","frown","fudge","fugue","fumble","funky","funny","furry","fuzzy",
  "gadget","galaxy","gallop","game","garden","garnet","gaze","gem","genial","genius","genuine","giant","giraffe","give","glass","glaze",
  "glide","glitter","glove","glue","gnome","goat","golf","goose","gorge","gourd","grace","grain","grant","graph","grate","gray",
  "great","greet","grin","ground","grove","guava","guide","guitar","gull","gust","habit","half","hall","hamster","handle","harbor",
  "harmony","harp","haven","hay","headline","heart","heaven","hedge","hello","helper","hen","herb","hero","heron","hiccup","hide",
  "highland","hip","hive","hobby","hold","holiday","home","honey","hook","hop","horizon","horse","host","hour","house","humble",
  "hummer","hurdle","husky","hymn","ibis","icing","idea","igloo","image","immense","impact","impress","indigo","ink","inn","insect",
  "inside","invite","iron","item","ivy","jacket","jaguar","jasmine","java","jazz","jelly","jersey","jiffy","jive","jockey","join",
  "jolly","journey","judge","juice","jumbo","jungle","juniper","jury","jute","kangaroo","keel","keeper","kernel","kettle","kibble","kid",
  "kind","kiosk","kiss","kite","kiwi","knack","knee","knit","knob","koala","lace","ladder","lagoon","lamb","lamp","land",
  "lantern","larch","laser","laugh","laundry","lava","lawn","leader","league","leather","ledge","lemon","lend","leopard","library","license",
  "light","lily","linen","liquid","listen","litter","lively","living","llama","loaf","lobster","local","locker","lodge","log","long",
  "loom","loot","loud","loyal","lucky","lumen","lunar","lung","luscious","lute","lyric","magic","magnet","mailbox","maker","mammoth",
  "manor","maple","marble","marigold","marker","marmot","mars","mask","mason","match","maven","meal","meatball","media","medium","melon",
  "memory","mentor","mercy","merge","merlin","mesa","metal","meter","middle","midnight","miller","mimic","mingle","minnow","mint","minute",
  "mirror","mist","mobile","model","modest","molar","money","monkey","month","moon","mop","morning","moth","motor","mouse","movie",
  "muffin","mulberry","mural","mushroom","muslin","mystery","napkin","nasturtium","nature","near","nebula","nectar","needle","nephew","nest","never",
  "newt","nice","nickel","nimble","noble","noise","noon","normal","nose","notice","number","oak","oat","ocean","octave","office",
  "olive","onion","onyx","opal","opera","option","orbit","orchard","order","oregano","origami","oriole","otter","outback","outing","oven",
  "oxen","pact","pagoda","pair","palace","palette","pancake","pansy","paper","parade","paradise","parcel","parrot","party","pastel","pastry",
  "patch","patio","pattern","pavilion","peacock","pear","pearl","pelican","pencil","penguin","peony","perch","perfect","person","petunia","phoenix",
  "photo","piano","picture","piece","pigeon","pilot","pineapple","pink","pioneer","pippin","pistachio","pixel","pizza","place","planet","plant",
  "platform","platter","plaza","pleasant","plum","pocket","poet","polar","pole","polish","pony","porch","portal","possum","postcard","potato",
  "pouch","power","praise","pretty","pretzel","prime","print","private","profile","proud","prune","pudding","pulley","puma","pumpkin","pupil",
  "puppet","purple","purr","puzzle","quail","quake","quantum","queen","quest","quiet","quilt","quince","quiver","rabbit","race","radio",
  "raft","rain","raisin","rake","rampart","range","raspberry","rattle","ray","read","recipe","record","recycle","redwood","reef","refresh",
  "region","relish","rely","render","rent","report","reserve","result","return","reward","rhubarb","rhythm","rice","rider","ridge","right",
  "ring","river","roam","robin","robot","rocket","rodeo","romance","rook","room","rope","rouge","route","rowan","rubber","ruby",
  "rug","rumor","rural","rustic","safari","safe","sage","salad","salon","salt","sample","sand","sandwich","sapphire","sauce","savor",
  "scale","scamp","scarf","scene","scholar","science","scooter","score","scramble","script","sculpt","seal","season","seaweed","secret","seedling",
  "select","senior","sentry","series","service","settle","shadow","shallow","shamrock","share","sharp","shelf","shelter","sherpa","shield","ship",
  "shirt","shore","shoulder","shower","shuttle","sienna","siesta","signal","silk","silly","silver","since","siren","sitar","skate","sketch",
  "skill","skipper","slate","sleek","sleeve","slide","slope","smile","snack","snap","sneaker","snug","soar","social","soft","solar",
  "soldier","solo","some","song","soon","sorrel","soul","soup","south","space","spark","speak","spear","sphere","spider","spine",
  "splash","spoke","sponge","spoon","spot","spray","sprout","spruce","squash","squirrel","stack","staff","stamp","star","stare","state",
  "steel","stem","stereo","stew","still","stitch","stone","stork","story","stove","straw","street","studio","style","sugar","suit",
  "sun","sunflower","sunrise","super","supper","support","surprise","swallow","sweater","swift","swim","syrup","tackle","tadpole","tailor","tally",
  "tame","tango","tapestry","tarragon","task","tater","tavern","teacher","teapot","teddy","temple","tempo","tender","tent","terrier","thatch",
  "theater","theme","thicket","think","thorn","three","throne","thrush","thyme","tide","tiger","timber","timer","tiny","tiptoe","title",
  "toast","toffee","tome","tongue","tool","topaz","torch","total","toucan","tour","town","track","traffic","train","trance","travel",
  "treat","trellis","tremolo","tribe","trinket","triumph","tropic","trove","truffle","trunk","truth","tulip","tundra","turban","turkey","turnip",
  "turret","tusk","twelve","twilight","twine","twinkle","twist","typhoon","under","union","unity","upbeat","urban","vacation","valiant","value",
  "vantage","vapor","vault","venture","verdant","vessel","veteran","vibe","view","village","violin","vista","vivid","volcano","voucher","waffle",
  "walk","wallet","walnut","waltz","wardrobe","warrior","water","waxwing","weather","weekend","welcome","whale","wheat","whim","whimsy","whisker",
  "whistle","widget","wild","win","winch","window","wing","wisdom","wisp","witty","wolf","wonder","wool","work","worm","worthy",
  "wren","write","yacht","yam","yarn","year","yeti","yodel","yogurt","young","zebra","zen","zest","zinc","zinnia","zodiac",
] as const;

if (WORDLIST.length !== 1024) {
  throw new Error(`WORDLIST must have exactly 1024 entries; got ${WORDLIST.length}`);
}
